// Code generated by GoGamePlug DO NOT EDIT.

package R

var (
	MAP     = newMap_h3jp4mzum5ff994j()
	RAW     = newRaw_8mq45yxgwb6zcnvi()
	AUDIO   = newAudio_f7z90octvnsbdt3j()
	IMAGE   = newImage_utv2j0o37paawu8s()
	SHADER  = newShader_lb40ao4ajzppxskk()
	SPRITE  = newSprite_6446ykphkhnnb0l1()
	TILESET = newTileset_8hbs2jloghbhjj9s()
	CLASS   = newClass_93ujaw4cdhx34prh()
	LAYER   = newLayer_t1t5lx55omuvagyp()
	OBJECT  = newObject_5mogzimq5arejyu7()
	PROP    = newProp_e1d3ektr5b1j05ht()
	TILE    = newTile_sjhwnqcmw3oetpmh()
	OTHER   = newOther_9utgd6wiz8dy78yx()
)

type map_h3jp4mzum5ff994j struct {
	MAIN string
}

func newMap_h3jp4mzum5ff994j() *map_h3jp4mzum5ff994j {
	return &map_h3jp4mzum5ff994j{MAIN: "res/map/main.tmx"}
}

type raw_8mq45yxgwb6zcnvi struct {
	IPSX_FONT string
}

func newRaw_8mq45yxgwb6zcnvi() *raw_8mq45yxgwb6zcnvi {
	return &raw_8mq45yxgwb6zcnvi{IPSX_FONT: "res/raw/ipsx_font.ttf"}
}

type audio_f7z90octvnsbdt3j struct {
}

func newAudio_f7z90octvnsbdt3j() *audio_f7z90octvnsbdt3j {
	return &audio_f7z90octvnsbdt3j{}
}

type image_utv2j0o37paawu8s struct {
	TILE  string
	OTHER string
}

func newImage_utv2j0o37paawu8s() *image_utv2j0o37paawu8s {
	return &image_utv2j0o37paawu8s{TILE: "res/image/tile.png", OTHER: "res/image/other.png"}
}

type shader_lb40ao4ajzppxskk struct {
}

func newShader_lb40ao4ajzppxskk() *shader_lb40ao4ajzppxskk {
	return &shader_lb40ao4ajzppxskk{}
}

type sprite_6446ykphkhnnb0l1 struct {
	TILE  string
	OTHER string
}

func newSprite_6446ykphkhnnb0l1() *sprite_6446ykphkhnnb0l1 {
	return &sprite_6446ykphkhnnb0l1{TILE: "res/sprite/tile.json", OTHER: "res/sprite/other.json"}
}

type tileset_8hbs2jloghbhjj9s struct {
	BG string
}

func newTileset_8hbs2jloghbhjj9s() *tileset_8hbs2jloghbhjj9s {
	return &tileset_8hbs2jloghbhjj9s{BG: "res/tileSet/bg.tsx"}
}

type class_93ujaw4cdhx34prh struct {
	CURSOR string
	TIP    string
	MENU   string
	PLAYER string
}

func newClass_93ujaw4cdhx34prh() *class_93ujaw4cdhx34prh {
	return &class_93ujaw4cdhx34prh{CURSOR: "cursor", TIP: "tip", MENU: "menu", PLAYER: "player"}
}

type layer_t1t5lx55omuvagyp struct {
	FG      string
	BG      string
	COMMAND string
	OBJECT  string
}

func newLayer_t1t5lx55omuvagyp() *layer_t1t5lx55omuvagyp {
	return &layer_t1t5lx55omuvagyp{FG: "fg", BG: "bg", COMMAND: "command", OBJECT: "object"}
}

type object_5mogzimq5arejyu7 struct {
	CURSOR string
	MARISA string
	SAKUYA string
	ALICE  string
	YOUMU  string
	TIP    string
	REIMU  string
	MENU   string
	REISEN string
}

func newObject_5mogzimq5arejyu7() *object_5mogzimq5arejyu7 {
	return &object_5mogzimq5arejyu7{CURSOR: "cursor", MARISA: "marisa", SAKUYA: "sakuya", ALICE: "alice", YOUMU: "youmu", TIP: "tip", REIMU: "reimu", MENU: "menu", REISEN: "reisen"}
}

type prop_e1d3ektr5b1j05ht struct {
	ENEMY string
}

func newProp_e1d3ektr5b1j05ht() *prop_e1d3ektr5b1j05ht {
	return &prop_e1d3ektr5b1j05ht{ENEMY: "enemy"}
}

type tile_sjhwnqcmw3oetpmh struct {
	TILE *tile_jwne26z8qefq1hm7
}

func newTile_sjhwnqcmw3oetpmh() *tile_sjhwnqcmw3oetpmh {
	return &tile_sjhwnqcmw3oetpmh{TILE: newTile_jwne26z8qefq1hm7()}
}

type tile_jwne26z8qefq1hm7 struct {
	CHAO  string
	HE    string
	PAO   string
	QIANG string
	SHA   string
	SHAN  string
	SHEN  string
	YAN   string
}

func newTile_jwne26z8qefq1hm7() *tile_jwne26z8qefq1hm7 {
	return &tile_jwne26z8qefq1hm7{CHAO: "tile/chao", HE: "tile/he", PAO: "tile/pao", QIANG: "tile/qiang", SHA: "tile/sha", SHAN: "tile/shan", SHEN: "tile/shen", YAN: "tile/yan"}
}

type other_9utgd6wiz8dy78yx struct {
	PLAYER *player_tprb0wkgegm6t58w
	OTHER  *other_yci33mwo09klfd1m
	EQUIP  *equip_t85bn3tbwxa2m079
	EFFECT *effect_g5e2svm9ykemas3d
}

func newOther_9utgd6wiz8dy78yx() *other_9utgd6wiz8dy78yx {
	return &other_9utgd6wiz8dy78yx{PLAYER: newPlayer_tprb0wkgegm6t58w(), OTHER: newOther_yci33mwo09klfd1m(), EQUIP: newEquip_t85bn3tbwxa2m079(), EFFECT: newEffect_g5e2svm9ykemas3d()}
}

type player_tprb0wkgegm6t58w struct {
	ALICE  string
	MARISA string
	REIMU  string
	REISEN string
	SAKUYA string
	YOUMU  string
}

func newPlayer_tprb0wkgegm6t58w() *player_tprb0wkgegm6t58w {
	return &player_tprb0wkgegm6t58w{ALICE: "player/alice", MARISA: "player/marisa", REIMU: "player/reimu", REISEN: "player/reisen", SAKUYA: "player/sakuya", YOUMU: "player/youmu"}
}

type other_yci33mwo09klfd1m struct {
	ARROW string
	POINT string
}

func newOther_yci33mwo09klfd1m() *other_yci33mwo09klfd1m {
	return &other_yci33mwo09klfd1m{ARROW: "other/arrow", POINT: "other/point"}
}

type equip_t85bn3tbwxa2m079 struct {
	BOOK    string
	BOW     string
	BOWKNOT string
	CLOAK   string
	HAT     string
	KNIFE   string
	PILL    string
	RING    string
	STAFF   string
}

func newEquip_t85bn3tbwxa2m079() *equip_t85bn3tbwxa2m079 {
	return &equip_t85bn3tbwxa2m079{BOOK: "equip/book", BOW: "equip/bow", BOWKNOT: "equip/bowknot", CLOAK: "equip/cloak", HAT: "equip/hat", KNIFE: "equip/knife", PILL: "equip/pill", RING: "equip/ring", STAFF: "equip/staff"}
}

type effect_g5e2svm9ykemas3d struct {
	ATTACK   string
	DELIVERY string
	RECOVERY string
	FIRE     string
}

func newEffect_g5e2svm9ykemas3d() *effect_g5e2svm9ykemas3d {
	return &effect_g5e2svm9ykemas3d{ATTACK: "effect/attack", DELIVERY: "effect/delivery", RECOVERY: "effect/recovery", FIRE: "effect/fire"}
}
